stages:
  prepare:
    cmd: poetry run python3 wine_quality_prediction_modeling/prepare.py
    deps:
    - data/raw
    - wine_quality_prediction_modeling/prepare.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  train:
    cmd: poetry run python3 wine_quality_prediction_modeling/train.py
    deps:
    - data/prepared/train.csv
    - wine_quality_prediction_modeling/train.py
    outs:
    - model/wine_quality_model.joblib
  evaluate:
    cmd: poetry run python3 wine_quality_prediction_modeling/evaluate.py
    deps:
    - model/wine_quality_model.joblib
    - wine_quality_prediction_modeling/evaluate.py
    metrics:
    - metrics/metrics.json:
        cache: false
