name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libc6
      - uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12.3
          poetry-version: 1.8.1
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Setup DagsHub DVC remote
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_TOKEN }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_TOKEN }}
      - name: Train model
        run: |
          dvc pull -r origin
          poetry install --only main
          dvc repro
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Compare metrics to main
          git fetch --depth=1 origin main:main
          dvc metrics diff --md main >> report.md
          cml comment create report.md
