name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      #   - uses: Gr1N/setup-poetry@v8
      - name: Setup Poetry
        uses: pronovic/setup-poetry@v2
        with:
          version: "1.8.0"
          plugins: "poetry-dynamic-versioning==1.2.0"
          cache-venv: "true"
          cache-poetry: "true"
      - name: Train model
        run: |
          dvc pull data
          pip install -r requirements.txt
          dvc repro
      - name: Create CML report
        run: |
          # Compare metrics to main
          git fetch --depth=1 origin main:main
          dvc metrics diff --show-md main >> report.md
          # Plot training loss function diff
          dvc plots diff \
            --target loss.csv --show-vega main > vega.json
          vl2png vega.json > plot.png
          echo '![](./plot.png "Training Loss")' >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
