name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      #   - uses: Gr1N/setup-poetry@v8
      #   - name: Setup Poetry
      #     uses: pronovic/setup-poetry@v2
      #     with:
      #       version: "1.8.0"
      #       plugins: "poetry-dynamic-versioning==1.2.0"
      #       cache-venv: "true"
      #       cache-poetry: "true"
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.1"
      - name: Setup DagsHub DVC remote
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_TOKEN }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_TOKEN }}
      - name: Train model
        run: |
          dvc pull -r origin
          poetry install --only main
          dvc repro
      - name: Create CML report
        run: |
          # Compare metrics to main
          dvc metrics diff main --md >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
